parameters:
  vmImage:

jobs:
  - job: Test_Windows
    displayName: Test Windows

    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        Python 2.7:
          python.version: "2.7"
        Python 3.4:
          python.version: "3.4"
        Python 3.5:
          python.version: "3.5"
        Python 3.6:
          python.version: "3.6"
        Python 3.7:
          python.version: "3.7"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install --upgrade codecov
          pip install -e .[test]
        displayName: "Install testing requirements"
      - script: py.test --cov=zeep --cov-report=term-missing"
        displayName: "Run pytest with for Python $(python.version)"
      - script: |
          codecov
        condition: succeeded()
        displayName: "Upload coverage information to codecov.io"
