parameters:
  vmImage:

jobs:
  - job: Test_Linux
    displayName: Test Linux

    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        Python 2.7:
          python.version: "2.7"
          TOXENV: "py27"
        Python 3.4:
          python.version: "3.4"
          TOXENV: "py34"
        Python 3.5:
          python.version: "3.5"
          TOXENV: "py35"
        Python 3.6:
          python.version: "3.6"
          TOXENV: "py36"
        Python 3.7:
          python.version: "3.7"
          TOXENV: "py37"

    steps:
      - script: sudo apt-get install -y
          libssl-dev
          libxmlsec1
          libxmlsec1-dev
          libxmlsec1-openssl
          libxslt1-dev
          pkg-config
        displayName: "Apt install dependencies"
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install --upgrade tox
          pip install --upgrade codecov
        displayName: "Install testing requirements"
      - script: tox -e $(TOXENV)
        displayName: "Run tox with TOXENV=$(TOXENV)"
      - script: |
          tox -e coverage-report
          codecov
        condition: succeeded()
        displayName: "Upload coverage information to codecov.io"
